# Generated by Django 4.1.6 on 2023-02-08 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ca62597d-1452-45bb-9ba2-4d93a5d6075f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
